# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0002_auto_20170212_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='organizations',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
