# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0004_assumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='assumption',
            name='entitys',
            field=models.ManyToManyField(to='stakeholder.Entity'),
        ),
    ]
