# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stakeholder', '0006_auto_20170212_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(max_length=21, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('name', models.CharField(default=None, max_length=150)),
                ('tagline', models.CharField(blank=True, default=None, max_length=150)),
                ('description', models.TextField(blank=True, default=None, max_length=500)),
                ('hex_color', models.CharField(blank=True, default='#4DB6AC', max_length=7)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='clusters',
            field=models.ManyToManyField(blank=True, default=None, to='stakeholder.Cluster'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='clusters',
            field=models.ManyToManyField(blank=True, default=None, to='stakeholder.Cluster'),
        ),
        migrations.AlterField(
            model_name='assumption',
            name='clusters',
            field=models.ManyToManyField(blank=True, default=None, to='stakeholder.Cluster'),
        ),
        migrations.AlterField(
            model_name='assumption',
            name='entitys',
            field=models.ManyToManyField(blank=True, default=None, to='stakeholder.Entity'),
        ),
        migrations.AlterField(
            model_name='assumption',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, default=None, to='stakeholder.Stakeholder'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='stakeholder.Entity'),
        ),
    ]
