# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0007_auto_20170213_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder_map',
            name='assumptions',
            field=models.ManyToManyField(blank=True, default=None, to='stakeholder.Assumption'),
        ),
        migrations.AddField(
            model_name='stakeholder_map',
            name='clusters',
            field=models.ManyToManyField(blank=True, default=None, to='stakeholder.Cluster'),
        ),
        migrations.AddField(
            model_name='stakeholder_map',
            name='entitys',
            field=models.ManyToManyField(blank=True, default=None, to='stakeholder.Entity'),
        ),
        migrations.AddField(
            model_name='stakeholder_map',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, default=None, to='stakeholder.Stakeholder'),
        ),
    ]
