# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopefear', '0002_auto_20170222_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='hopefear_map',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hopefear.Hopefear_Map'),
        ),
    ]
