# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopefear', '0003_thought_hopefear_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='emotion',
            field=models.IntegerField(choices=[(1, 'Undeclared'), (2, 'Hope'), (3, 'Fear')], default=0),
        ),
    ]
