# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopefear', '0004_auto_20170223_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='project',
        ),
    ]
